#spring:
#  mail:
#    password: qgvmcsvyxzpeucrp
#    username: conttesttest4@gmail.com
#    host: smtp.gmail.com
#    port: 587
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true